export const IMAGE_CROPPER_ADD = 'IMAGE_CROPPER_ADD'
export const IMAGE_CROPPER_UPDATE = 'IMAGE_CROPPER_UPDATE'
export const IMAGE_CROPPER_DELETE = 'IMAGE_CROPPER_DELETE'
export const IMAGE_CROPPER_SET = 'IMAGE_CROPPER_SET'
