dist: trusty

sudo: false

language: node_js

node_js:
  - 8 # runtime used within Firebase functions

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - master
    - stage
    - prod
    - /^greenkeeper/.*$/

cache:
  directories:
    - $HOME/.npm

install:
  - npm i
  - npm i firebase-ci@^0.5.0 # install deps used in creating config and deploying

script:
  - npm run build:config # create env specific src/config.js
  - npm run lint
  - npm run test
  - npm run build

# addons:
#   code_climate:
#     repo_token: $CODE_CLIMATE

after_success:
  - npx semantic-release
  - npm run deploy # deploy without CI actions since createConfig is called earlier
