# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1

executors:
  create-container:
    working_directory: ~/repo
    docker:
      - image: cypress/base:8

jobs:
  building:
    executor: create-container
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn build:config --project "testing"
      - run: yarn lint
      # run tests!
      - run: yarn test
      - run: yarn build
      - run: cd ..
      - save_cache:
          paths:
            - ./
          key: build-cache-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  e2e-testing:
    executor: create-container
    parallelism: 2
    steps:
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_WORKFLOW_ID }}
            # fallback to using the latest cache if no exact match is found
            - build-cache
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn e2e:ci
      # - store_test_results:
      #     path: multiple-results
      # - store_artifacts:
      #     path: cypress/videos
      # - store_artifacts:
      #     path: cypress/screenshots
  deploying:
    executor: create-container
    steps:
      - restore_cache:
          keys:
            - build-cache-{{ .Environment.CIRCLE_WORKFLOW_ID }}
            # fallback to using the latest cache if no exact match is found
            - build-cache
      - run: yarn build:config
      - run: yarn build
      - run: npx semantic-release
      - run: yarn deploy

workflows:
  version: 2.1
  g2g:
    jobs:
      - building
      - e2e-testing:
          requires:
            - building
      - deploying:
          # type: approval
          filters:
            branches:
              only:
                - master
                - /rc-.*/
          requires:
            - building
            - e2e-testing
